org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

systemProp.https.protocols=TLSv1.2,TLSv1.3

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,)
neo_version=26.1.2.71
neo_version_range=[26.1.2,)

mod_version=1.0.0
mod_id=examplemod
mod_name=ExampleMod
mod_group_id=com.example
mod_description=Description
mod_url=
mod_issue_tracker=
mod_authors=Your Name
mod_license=License
