[versions]
minecraft = "1.21.1"         # Minecraft game version
neoForge = "21.1.238"        # NeoForge framework version
loader = "4"
parchment = "2024.11.17" # https://parchmentmc.org/docs/getting-started

modDevGradle = "2.0.86"      # NeoForge ModDevGradle plugin version
spotless = "8.1.0"           # Spotless code formatter plugin version
lombok = "8.13.1"            # Lombok plugin version

[plugins]
modDevGradle            = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
spotless                = { id = "com.diffplug.spotless", version.ref = "spotless" }
lombok                  = { id = "io.freefair.lombok", version.ref = "lombok" }
